/* This file generated by gen-mt-compat.pl at Thu Jul  3 18:56:23 2014 */
#ifndef LCB_MT_COMPAT_H
#define LCB_MT_COMPAT_H
#define lcb_unlock3 lcb__NTS_lcb_unlock3
#define lcb_create lcb__NTS_lcb_create
#define lcb_remove lcb__NTS_lcb_remove
#define lcb_get lcb__NTS_lcb_get
#define lcb_sched_enter lcb__NTS_lcb_sched_enter
#define lcb_store3 lcb__NTS_lcb_store3
#define lcb_server_stats lcb__NTS_lcb_server_stats
#define lcb_touch3 lcb__NTS_lcb_touch3
#define lcb_wait lcb__NTS_lcb_wait
#define lcb_remove3 lcb__NTS_lcb_remove3
#define lcb_sched_leave lcb__NTS_lcb_sched_leave
#define lcb_store lcb__NTS_lcb_store
#define lcb_touch lcb__NTS_lcb_touch
#define lcb_stats3 lcb__NTS_lcb_stats3
#define lcb_arithmetic lcb__NTS_lcb_arithmetic
#define lcb_get3 lcb__NTS_lcb_get3
#define lcb_install_callback3 lcb__NTS_lcb_install_callback3
#define lcb_counter3 lcb__NTS_lcb_counter3
#define lcb_connect lcb__NTS_lcb_connect
#define lcb_unlock lcb__NTS_lcb_unlock
/* Now include stuff */
#include <libcouchbase/mt.h>
#undef lcb_unlock3
#define lcb_unlock3(obj, cookie, cmd) lcbmt__Wwrap3(obj, cookie, cmd, "lcb_unlock3")
#undef lcb_create
#define lcb_create lcbmt_create
#undef lcb_remove
#define lcb_remove(obj, cookie, num, cmds) lcbmt__Wwrap2(obj, cookie, num, (const void * const *)cmds, "lcb_remove")
#undef lcb_get
#define lcb_get(obj, cookie, num, cmds) lcbmt__Wwrap2(obj, cookie, num, (const void * const *)cmds, "lcb_get")
#undef lcb_sched_enter
#define lcb_sched_enter lcbmt__Wenter3
#undef lcb_store3
#define lcb_store3(obj, cookie, cmd) lcbmt__Wwrap3(obj, cookie, cmd, "lcb_store3")
#undef lcb_server_stats
#define lcb_server_stats(obj, cookie, num, cmds) lcbmt__Wwrap2(obj, cookie, num, (const void * const *)cmds, "lcb_server_stats")
#undef lcb_touch3
#define lcb_touch3(obj, cookie, cmd) lcbmt__Wwrap3(obj, cookie, cmd, "lcb_touch3")
#undef lcb_wait
#define lcb_wait lcbmt__Wwait
#undef lcb_remove3
#define lcb_remove3(obj, cookie, cmd) lcbmt__Wwrap3(obj, cookie, cmd, "lcb_remove3")
#undef lcb_sched_leave
#define lcb_sched_leave lcbmt__Wleave3
#undef lcb_store
#define lcb_store(obj, cookie, num, cmds) lcbmt__Wwrap2(obj, cookie, num, (const void * const *)cmds, "lcb_store")
#undef lcb_touch
#define lcb_touch(obj, cookie, num, cmds) lcbmt__Wwrap2(obj, cookie, num, (const void * const *)cmds, "lcb_touch")
#undef lcb_stats3
#define lcb_stats3(obj, cookie, cmd) lcbmt__Wwrap3(obj, cookie, cmd, "lcb_stats3")
#undef lcb_arithmetic
#define lcb_arithmetic(obj, cookie, num, cmds) lcbmt__Wwrap2(obj, cookie, num, (const void * const *)cmds, "lcb_arithmetic")
#undef lcb_get3
#define lcb_get3(obj, cookie, cmd) lcbmt__Wwrap3(obj, cookie, cmd, "lcb_get3")
#undef lcb_install_callback3
#define lcb_install_callback3 lcbmt_install_callback
#undef lcb_counter3
#define lcb_counter3(obj, cookie, cmd) lcbmt__Wwrap3(obj, cookie, cmd, "lcb_counter3")
#undef lcb_connect
#define lcb_connect lcbmt__Wconnect
#undef lcb_unlock
#define lcb_unlock(obj, cookie, num, cmds) lcbmt__Wwrap2(obj, cookie, num, (const void * const *)cmds, "lcb_unlock")
#endif
