/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_query_2eproto__INCLUDED
#define PROTOBUF_C_query_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _Q2i__Error Q2i__Error;
typedef struct _Q2i__QueryPayload Q2i__QueryPayload;
typedef struct _Q2i__StatisticsRequest Q2i__StatisticsRequest;
typedef struct _Q2i__StatisticsResponse Q2i__StatisticsResponse;
typedef struct _Q2i__ScanRequest Q2i__ScanRequest;
typedef struct _Q2i__ScanAllRequest Q2i__ScanAllRequest;
typedef struct _Q2i__EndStreamRequest Q2i__EndStreamRequest;
typedef struct _Q2i__ResponseStream Q2i__ResponseStream;
typedef struct _Q2i__StreamEndResponse Q2i__StreamEndResponse;
typedef struct _Q2i__CountRequest Q2i__CountRequest;
typedef struct _Q2i__CountResponse Q2i__CountResponse;
typedef struct _Q2i__Span Q2i__Span;
typedef struct _Q2i__Range Q2i__Range;
typedef struct _Q2i__IndexEntry Q2i__IndexEntry;
typedef struct _Q2i__IndexStatistics Q2i__IndexStatistics;


/* --- enums --- */


/* --- messages --- */

struct  _Q2i__Error
{
  ProtobufCMessage base;
  char *error;
};
#define Q2I__ERROR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&q2i__error__descriptor) \
    , NULL }


struct  _Q2i__QueryPayload
{
  ProtobufCMessage base;
  uint32_t version;
  Q2i__StatisticsRequest *statisticsrequest;
  Q2i__StatisticsResponse *statistics;
  Q2i__ScanRequest *scanrequest;
  Q2i__ScanAllRequest *scanallrequest;
  Q2i__ResponseStream *stream;
  Q2i__CountRequest *countrequest;
  Q2i__CountResponse *countresponse;
  Q2i__EndStreamRequest *endstream;
  Q2i__StreamEndResponse *streamend;
};
#define Q2I__QUERY_PAYLOAD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&q2i__query_payload__descriptor) \
    , 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }


struct  _Q2i__StatisticsRequest
{
  ProtobufCMessage base;
  Q2i__Span *span;
  char *indexname;
  char *bucket;
};
#define Q2I__STATISTICS_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&q2i__statistics_request__descriptor) \
    , NULL, NULL, NULL }


struct  _Q2i__StatisticsResponse
{
  ProtobufCMessage base;
  Q2i__IndexStatistics *stats;
  Q2i__Error *err;
};
#define Q2I__STATISTICS_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&q2i__statistics_response__descriptor) \
    , NULL, NULL }


struct  _Q2i__ScanRequest
{
  ProtobufCMessage base;
  Q2i__Span *span;
  protobuf_c_boolean distinct;
  int64_t limit;
  int64_t pagesize;
  char *indexname;
  char *bucket;
};
#define Q2I__SCAN_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&q2i__scan_request__descriptor) \
    , NULL, 0, 0, 0, NULL, NULL }


struct  _Q2i__ScanAllRequest
{
  ProtobufCMessage base;
  int64_t pagesize;
  int64_t limit;
  char *indexname;
  char *bucket;
};
#define Q2I__SCAN_ALL_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&q2i__scan_all_request__descriptor) \
    , 0, 0, NULL, NULL }


struct  _Q2i__EndStreamRequest
{
  ProtobufCMessage base;
};
#define Q2I__END_STREAM_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&q2i__end_stream_request__descriptor) \
     }


struct  _Q2i__ResponseStream
{
  ProtobufCMessage base;
  size_t n_indexentries;
  Q2i__IndexEntry **indexentries;
  Q2i__Error *err;
};
#define Q2I__RESPONSE_STREAM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&q2i__response_stream__descriptor) \
    , 0,NULL, NULL }


struct  _Q2i__StreamEndResponse
{
  ProtobufCMessage base;
  Q2i__Error *err;
};
#define Q2I__STREAM_END_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&q2i__stream_end_response__descriptor) \
    , NULL }


struct  _Q2i__CountRequest
{
  ProtobufCMessage base;
  char *indexname;
  char *bucket;
};
#define Q2I__COUNT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&q2i__count_request__descriptor) \
    , NULL, NULL }


struct  _Q2i__CountResponse
{
  ProtobufCMessage base;
  int64_t count;
  Q2i__Error *err;
};
#define Q2I__COUNT_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&q2i__count_response__descriptor) \
    , 0, NULL }


struct  _Q2i__Span
{
  ProtobufCMessage base;
  Q2i__Range *range;
  size_t n_equal;
  ProtobufCBinaryData *equal;
};
#define Q2I__SPAN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&q2i__span__descriptor) \
    , NULL, 0,NULL }


struct  _Q2i__Range
{
  ProtobufCMessage base;
  ProtobufCBinaryData low;
  ProtobufCBinaryData high;
  uint32_t inclusion;
};
#define Q2I__RANGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&q2i__range__descriptor) \
    , {0,NULL}, {0,NULL}, 0 }


struct  _Q2i__IndexEntry
{
  ProtobufCMessage base;
  ProtobufCBinaryData entrykey;
  ProtobufCBinaryData primarykey;
};
#define Q2I__INDEX_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&q2i__index_entry__descriptor) \
    , {0,NULL}, {0,NULL} }


struct  _Q2i__IndexStatistics
{
  ProtobufCMessage base;
  uint64_t keyscount;
  uint64_t uniquekeyscount;
  ProtobufCBinaryData keymin;
  ProtobufCBinaryData keymax;
};
#define Q2I__INDEX_STATISTICS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&q2i__index_statistics__descriptor) \
    , 0, 0, {0,NULL}, {0,NULL} }


/* Q2i__Error methods */
void   q2i__error__init
                     (Q2i__Error         *message);
size_t q2i__error__get_packed_size
                     (const Q2i__Error   *message);
size_t q2i__error__pack
                     (const Q2i__Error   *message,
                      uint8_t             *out);
size_t q2i__error__pack_to_buffer
                     (const Q2i__Error   *message,
                      ProtobufCBuffer     *buffer);
Q2i__Error *
       q2i__error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   q2i__error__free_unpacked
                     (Q2i__Error *message,
                      ProtobufCAllocator *allocator);
/* Q2i__QueryPayload methods */
void   q2i__query_payload__init
                     (Q2i__QueryPayload         *message);
size_t q2i__query_payload__get_packed_size
                     (const Q2i__QueryPayload   *message);
size_t q2i__query_payload__pack
                     (const Q2i__QueryPayload   *message,
                      uint8_t             *out);
size_t q2i__query_payload__pack_to_buffer
                     (const Q2i__QueryPayload   *message,
                      ProtobufCBuffer     *buffer);
Q2i__QueryPayload *
       q2i__query_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   q2i__query_payload__free_unpacked
                     (Q2i__QueryPayload *message,
                      ProtobufCAllocator *allocator);
/* Q2i__StatisticsRequest methods */
void   q2i__statistics_request__init
                     (Q2i__StatisticsRequest         *message);
size_t q2i__statistics_request__get_packed_size
                     (const Q2i__StatisticsRequest   *message);
size_t q2i__statistics_request__pack
                     (const Q2i__StatisticsRequest   *message,
                      uint8_t             *out);
size_t q2i__statistics_request__pack_to_buffer
                     (const Q2i__StatisticsRequest   *message,
                      ProtobufCBuffer     *buffer);
Q2i__StatisticsRequest *
       q2i__statistics_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   q2i__statistics_request__free_unpacked
                     (Q2i__StatisticsRequest *message,
                      ProtobufCAllocator *allocator);
/* Q2i__StatisticsResponse methods */
void   q2i__statistics_response__init
                     (Q2i__StatisticsResponse         *message);
size_t q2i__statistics_response__get_packed_size
                     (const Q2i__StatisticsResponse   *message);
size_t q2i__statistics_response__pack
                     (const Q2i__StatisticsResponse   *message,
                      uint8_t             *out);
size_t q2i__statistics_response__pack_to_buffer
                     (const Q2i__StatisticsResponse   *message,
                      ProtobufCBuffer     *buffer);
Q2i__StatisticsResponse *
       q2i__statistics_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   q2i__statistics_response__free_unpacked
                     (Q2i__StatisticsResponse *message,
                      ProtobufCAllocator *allocator);
/* Q2i__ScanRequest methods */
void   q2i__scan_request__init
                     (Q2i__ScanRequest         *message);
size_t q2i__scan_request__get_packed_size
                     (const Q2i__ScanRequest   *message);
size_t q2i__scan_request__pack
                     (const Q2i__ScanRequest   *message,
                      uint8_t             *out);
size_t q2i__scan_request__pack_to_buffer
                     (const Q2i__ScanRequest   *message,
                      ProtobufCBuffer     *buffer);
Q2i__ScanRequest *
       q2i__scan_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   q2i__scan_request__free_unpacked
                     (Q2i__ScanRequest *message,
                      ProtobufCAllocator *allocator);
/* Q2i__ScanAllRequest methods */
void   q2i__scan_all_request__init
                     (Q2i__ScanAllRequest         *message);
size_t q2i__scan_all_request__get_packed_size
                     (const Q2i__ScanAllRequest   *message);
size_t q2i__scan_all_request__pack
                     (const Q2i__ScanAllRequest   *message,
                      uint8_t             *out);
size_t q2i__scan_all_request__pack_to_buffer
                     (const Q2i__ScanAllRequest   *message,
                      ProtobufCBuffer     *buffer);
Q2i__ScanAllRequest *
       q2i__scan_all_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   q2i__scan_all_request__free_unpacked
                     (Q2i__ScanAllRequest *message,
                      ProtobufCAllocator *allocator);
/* Q2i__EndStreamRequest methods */
void   q2i__end_stream_request__init
                     (Q2i__EndStreamRequest         *message);
size_t q2i__end_stream_request__get_packed_size
                     (const Q2i__EndStreamRequest   *message);
size_t q2i__end_stream_request__pack
                     (const Q2i__EndStreamRequest   *message,
                      uint8_t             *out);
size_t q2i__end_stream_request__pack_to_buffer
                     (const Q2i__EndStreamRequest   *message,
                      ProtobufCBuffer     *buffer);
Q2i__EndStreamRequest *
       q2i__end_stream_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   q2i__end_stream_request__free_unpacked
                     (Q2i__EndStreamRequest *message,
                      ProtobufCAllocator *allocator);
/* Q2i__ResponseStream methods */
void   q2i__response_stream__init
                     (Q2i__ResponseStream         *message);
size_t q2i__response_stream__get_packed_size
                     (const Q2i__ResponseStream   *message);
size_t q2i__response_stream__pack
                     (const Q2i__ResponseStream   *message,
                      uint8_t             *out);
size_t q2i__response_stream__pack_to_buffer
                     (const Q2i__ResponseStream   *message,
                      ProtobufCBuffer     *buffer);
Q2i__ResponseStream *
       q2i__response_stream__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   q2i__response_stream__free_unpacked
                     (Q2i__ResponseStream *message,
                      ProtobufCAllocator *allocator);
/* Q2i__StreamEndResponse methods */
void   q2i__stream_end_response__init
                     (Q2i__StreamEndResponse         *message);
size_t q2i__stream_end_response__get_packed_size
                     (const Q2i__StreamEndResponse   *message);
size_t q2i__stream_end_response__pack
                     (const Q2i__StreamEndResponse   *message,
                      uint8_t             *out);
size_t q2i__stream_end_response__pack_to_buffer
                     (const Q2i__StreamEndResponse   *message,
                      ProtobufCBuffer     *buffer);
Q2i__StreamEndResponse *
       q2i__stream_end_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   q2i__stream_end_response__free_unpacked
                     (Q2i__StreamEndResponse *message,
                      ProtobufCAllocator *allocator);
/* Q2i__CountRequest methods */
void   q2i__count_request__init
                     (Q2i__CountRequest         *message);
size_t q2i__count_request__get_packed_size
                     (const Q2i__CountRequest   *message);
size_t q2i__count_request__pack
                     (const Q2i__CountRequest   *message,
                      uint8_t             *out);
size_t q2i__count_request__pack_to_buffer
                     (const Q2i__CountRequest   *message,
                      ProtobufCBuffer     *buffer);
Q2i__CountRequest *
       q2i__count_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   q2i__count_request__free_unpacked
                     (Q2i__CountRequest *message,
                      ProtobufCAllocator *allocator);
/* Q2i__CountResponse methods */
void   q2i__count_response__init
                     (Q2i__CountResponse         *message);
size_t q2i__count_response__get_packed_size
                     (const Q2i__CountResponse   *message);
size_t q2i__count_response__pack
                     (const Q2i__CountResponse   *message,
                      uint8_t             *out);
size_t q2i__count_response__pack_to_buffer
                     (const Q2i__CountResponse   *message,
                      ProtobufCBuffer     *buffer);
Q2i__CountResponse *
       q2i__count_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   q2i__count_response__free_unpacked
                     (Q2i__CountResponse *message,
                      ProtobufCAllocator *allocator);
/* Q2i__Span methods */
void   q2i__span__init
                     (Q2i__Span         *message);
size_t q2i__span__get_packed_size
                     (const Q2i__Span   *message);
size_t q2i__span__pack
                     (const Q2i__Span   *message,
                      uint8_t             *out);
size_t q2i__span__pack_to_buffer
                     (const Q2i__Span   *message,
                      ProtobufCBuffer     *buffer);
Q2i__Span *
       q2i__span__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   q2i__span__free_unpacked
                     (Q2i__Span *message,
                      ProtobufCAllocator *allocator);
/* Q2i__Range methods */
void   q2i__range__init
                     (Q2i__Range         *message);
size_t q2i__range__get_packed_size
                     (const Q2i__Range   *message);
size_t q2i__range__pack
                     (const Q2i__Range   *message,
                      uint8_t             *out);
size_t q2i__range__pack_to_buffer
                     (const Q2i__Range   *message,
                      ProtobufCBuffer     *buffer);
Q2i__Range *
       q2i__range__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   q2i__range__free_unpacked
                     (Q2i__Range *message,
                      ProtobufCAllocator *allocator);
/* Q2i__IndexEntry methods */
void   q2i__index_entry__init
                     (Q2i__IndexEntry         *message);
size_t q2i__index_entry__get_packed_size
                     (const Q2i__IndexEntry   *message);
size_t q2i__index_entry__pack
                     (const Q2i__IndexEntry   *message,
                      uint8_t             *out);
size_t q2i__index_entry__pack_to_buffer
                     (const Q2i__IndexEntry   *message,
                      ProtobufCBuffer     *buffer);
Q2i__IndexEntry *
       q2i__index_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   q2i__index_entry__free_unpacked
                     (Q2i__IndexEntry *message,
                      ProtobufCAllocator *allocator);
/* Q2i__IndexStatistics methods */
void   q2i__index_statistics__init
                     (Q2i__IndexStatistics         *message);
size_t q2i__index_statistics__get_packed_size
                     (const Q2i__IndexStatistics   *message);
size_t q2i__index_statistics__pack
                     (const Q2i__IndexStatistics   *message,
                      uint8_t             *out);
size_t q2i__index_statistics__pack_to_buffer
                     (const Q2i__IndexStatistics   *message,
                      ProtobufCBuffer     *buffer);
Q2i__IndexStatistics *
       q2i__index_statistics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   q2i__index_statistics__free_unpacked
                     (Q2i__IndexStatistics *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Q2i__Error_Closure)
                 (const Q2i__Error *message,
                  void *closure_data);
typedef void (*Q2i__QueryPayload_Closure)
                 (const Q2i__QueryPayload *message,
                  void *closure_data);
typedef void (*Q2i__StatisticsRequest_Closure)
                 (const Q2i__StatisticsRequest *message,
                  void *closure_data);
typedef void (*Q2i__StatisticsResponse_Closure)
                 (const Q2i__StatisticsResponse *message,
                  void *closure_data);
typedef void (*Q2i__ScanRequest_Closure)
                 (const Q2i__ScanRequest *message,
                  void *closure_data);
typedef void (*Q2i__ScanAllRequest_Closure)
                 (const Q2i__ScanAllRequest *message,
                  void *closure_data);
typedef void (*Q2i__EndStreamRequest_Closure)
                 (const Q2i__EndStreamRequest *message,
                  void *closure_data);
typedef void (*Q2i__ResponseStream_Closure)
                 (const Q2i__ResponseStream *message,
                  void *closure_data);
typedef void (*Q2i__StreamEndResponse_Closure)
                 (const Q2i__StreamEndResponse *message,
                  void *closure_data);
typedef void (*Q2i__CountRequest_Closure)
                 (const Q2i__CountRequest *message,
                  void *closure_data);
typedef void (*Q2i__CountResponse_Closure)
                 (const Q2i__CountResponse *message,
                  void *closure_data);
typedef void (*Q2i__Span_Closure)
                 (const Q2i__Span *message,
                  void *closure_data);
typedef void (*Q2i__Range_Closure)
                 (const Q2i__Range *message,
                  void *closure_data);
typedef void (*Q2i__IndexEntry_Closure)
                 (const Q2i__IndexEntry *message,
                  void *closure_data);
typedef void (*Q2i__IndexStatistics_Closure)
                 (const Q2i__IndexStatistics *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor q2i__error__descriptor;
extern const ProtobufCMessageDescriptor q2i__query_payload__descriptor;
extern const ProtobufCMessageDescriptor q2i__statistics_request__descriptor;
extern const ProtobufCMessageDescriptor q2i__statistics_response__descriptor;
extern const ProtobufCMessageDescriptor q2i__scan_request__descriptor;
extern const ProtobufCMessageDescriptor q2i__scan_all_request__descriptor;
extern const ProtobufCMessageDescriptor q2i__end_stream_request__descriptor;
extern const ProtobufCMessageDescriptor q2i__response_stream__descriptor;
extern const ProtobufCMessageDescriptor q2i__stream_end_response__descriptor;
extern const ProtobufCMessageDescriptor q2i__count_request__descriptor;
extern const ProtobufCMessageDescriptor q2i__count_response__descriptor;
extern const ProtobufCMessageDescriptor q2i__span__descriptor;
extern const ProtobufCMessageDescriptor q2i__range__descriptor;
extern const ProtobufCMessageDescriptor q2i__index_entry__descriptor;
extern const ProtobufCMessageDescriptor q2i__index_statistics__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_query_2eproto__INCLUDED */
