/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "query.pb-c.h"
void   q2i__error__init
                     (Q2i__Error         *message)
{
  static Q2i__Error init_value = Q2I__ERROR__INIT;
  *message = init_value;
}
size_t q2i__error__get_packed_size
                     (const Q2i__Error *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t q2i__error__pack
                     (const Q2i__Error *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t q2i__error__pack_to_buffer
                     (const Q2i__Error *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Q2i__Error *
       q2i__error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Q2i__Error *)
     protobuf_c_message_unpack (&q2i__error__descriptor,
                                allocator, len, data);
}
void   q2i__error__free_unpacked
                     (Q2i__Error *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   q2i__query_payload__init
                     (Q2i__QueryPayload         *message)
{
  static Q2i__QueryPayload init_value = Q2I__QUERY_PAYLOAD__INIT;
  *message = init_value;
}
size_t q2i__query_payload__get_packed_size
                     (const Q2i__QueryPayload *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__query_payload__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t q2i__query_payload__pack
                     (const Q2i__QueryPayload *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__query_payload__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t q2i__query_payload__pack_to_buffer
                     (const Q2i__QueryPayload *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__query_payload__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Q2i__QueryPayload *
       q2i__query_payload__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Q2i__QueryPayload *)
     protobuf_c_message_unpack (&q2i__query_payload__descriptor,
                                allocator, len, data);
}
void   q2i__query_payload__free_unpacked
                     (Q2i__QueryPayload *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__query_payload__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   q2i__statistics_request__init
                     (Q2i__StatisticsRequest         *message)
{
  static Q2i__StatisticsRequest init_value = Q2I__STATISTICS_REQUEST__INIT;
  *message = init_value;
}
size_t q2i__statistics_request__get_packed_size
                     (const Q2i__StatisticsRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__statistics_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t q2i__statistics_request__pack
                     (const Q2i__StatisticsRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__statistics_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t q2i__statistics_request__pack_to_buffer
                     (const Q2i__StatisticsRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__statistics_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Q2i__StatisticsRequest *
       q2i__statistics_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Q2i__StatisticsRequest *)
     protobuf_c_message_unpack (&q2i__statistics_request__descriptor,
                                allocator, len, data);
}
void   q2i__statistics_request__free_unpacked
                     (Q2i__StatisticsRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__statistics_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   q2i__statistics_response__init
                     (Q2i__StatisticsResponse         *message)
{
  static Q2i__StatisticsResponse init_value = Q2I__STATISTICS_RESPONSE__INIT;
  *message = init_value;
}
size_t q2i__statistics_response__get_packed_size
                     (const Q2i__StatisticsResponse *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__statistics_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t q2i__statistics_response__pack
                     (const Q2i__StatisticsResponse *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__statistics_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t q2i__statistics_response__pack_to_buffer
                     (const Q2i__StatisticsResponse *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__statistics_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Q2i__StatisticsResponse *
       q2i__statistics_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Q2i__StatisticsResponse *)
     protobuf_c_message_unpack (&q2i__statistics_response__descriptor,
                                allocator, len, data);
}
void   q2i__statistics_response__free_unpacked
                     (Q2i__StatisticsResponse *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__statistics_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   q2i__scan_request__init
                     (Q2i__ScanRequest         *message)
{
  static Q2i__ScanRequest init_value = Q2I__SCAN_REQUEST__INIT;
  *message = init_value;
}
size_t q2i__scan_request__get_packed_size
                     (const Q2i__ScanRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__scan_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t q2i__scan_request__pack
                     (const Q2i__ScanRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__scan_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t q2i__scan_request__pack_to_buffer
                     (const Q2i__ScanRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__scan_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Q2i__ScanRequest *
       q2i__scan_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Q2i__ScanRequest *)
     protobuf_c_message_unpack (&q2i__scan_request__descriptor,
                                allocator, len, data);
}
void   q2i__scan_request__free_unpacked
                     (Q2i__ScanRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__scan_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   q2i__scan_all_request__init
                     (Q2i__ScanAllRequest         *message)
{
  static Q2i__ScanAllRequest init_value = Q2I__SCAN_ALL_REQUEST__INIT;
  *message = init_value;
}
size_t q2i__scan_all_request__get_packed_size
                     (const Q2i__ScanAllRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__scan_all_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t q2i__scan_all_request__pack
                     (const Q2i__ScanAllRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__scan_all_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t q2i__scan_all_request__pack_to_buffer
                     (const Q2i__ScanAllRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__scan_all_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Q2i__ScanAllRequest *
       q2i__scan_all_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Q2i__ScanAllRequest *)
     protobuf_c_message_unpack (&q2i__scan_all_request__descriptor,
                                allocator, len, data);
}
void   q2i__scan_all_request__free_unpacked
                     (Q2i__ScanAllRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__scan_all_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   q2i__end_stream_request__init
                     (Q2i__EndStreamRequest         *message)
{
  static Q2i__EndStreamRequest init_value = Q2I__END_STREAM_REQUEST__INIT;
  *message = init_value;
}
size_t q2i__end_stream_request__get_packed_size
                     (const Q2i__EndStreamRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__end_stream_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t q2i__end_stream_request__pack
                     (const Q2i__EndStreamRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__end_stream_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t q2i__end_stream_request__pack_to_buffer
                     (const Q2i__EndStreamRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__end_stream_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Q2i__EndStreamRequest *
       q2i__end_stream_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Q2i__EndStreamRequest *)
     protobuf_c_message_unpack (&q2i__end_stream_request__descriptor,
                                allocator, len, data);
}
void   q2i__end_stream_request__free_unpacked
                     (Q2i__EndStreamRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__end_stream_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   q2i__response_stream__init
                     (Q2i__ResponseStream         *message)
{
  static Q2i__ResponseStream init_value = Q2I__RESPONSE_STREAM__INIT;
  *message = init_value;
}
size_t q2i__response_stream__get_packed_size
                     (const Q2i__ResponseStream *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__response_stream__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t q2i__response_stream__pack
                     (const Q2i__ResponseStream *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__response_stream__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t q2i__response_stream__pack_to_buffer
                     (const Q2i__ResponseStream *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__response_stream__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Q2i__ResponseStream *
       q2i__response_stream__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Q2i__ResponseStream *)
     protobuf_c_message_unpack (&q2i__response_stream__descriptor,
                                allocator, len, data);
}
void   q2i__response_stream__free_unpacked
                     (Q2i__ResponseStream *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__response_stream__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   q2i__stream_end_response__init
                     (Q2i__StreamEndResponse         *message)
{
  static Q2i__StreamEndResponse init_value = Q2I__STREAM_END_RESPONSE__INIT;
  *message = init_value;
}
size_t q2i__stream_end_response__get_packed_size
                     (const Q2i__StreamEndResponse *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__stream_end_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t q2i__stream_end_response__pack
                     (const Q2i__StreamEndResponse *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__stream_end_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t q2i__stream_end_response__pack_to_buffer
                     (const Q2i__StreamEndResponse *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__stream_end_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Q2i__StreamEndResponse *
       q2i__stream_end_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Q2i__StreamEndResponse *)
     protobuf_c_message_unpack (&q2i__stream_end_response__descriptor,
                                allocator, len, data);
}
void   q2i__stream_end_response__free_unpacked
                     (Q2i__StreamEndResponse *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__stream_end_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   q2i__count_request__init
                     (Q2i__CountRequest         *message)
{
  static Q2i__CountRequest init_value = Q2I__COUNT_REQUEST__INIT;
  *message = init_value;
}
size_t q2i__count_request__get_packed_size
                     (const Q2i__CountRequest *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__count_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t q2i__count_request__pack
                     (const Q2i__CountRequest *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__count_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t q2i__count_request__pack_to_buffer
                     (const Q2i__CountRequest *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__count_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Q2i__CountRequest *
       q2i__count_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Q2i__CountRequest *)
     protobuf_c_message_unpack (&q2i__count_request__descriptor,
                                allocator, len, data);
}
void   q2i__count_request__free_unpacked
                     (Q2i__CountRequest *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__count_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   q2i__count_response__init
                     (Q2i__CountResponse         *message)
{
  static Q2i__CountResponse init_value = Q2I__COUNT_RESPONSE__INIT;
  *message = init_value;
}
size_t q2i__count_response__get_packed_size
                     (const Q2i__CountResponse *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__count_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t q2i__count_response__pack
                     (const Q2i__CountResponse *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__count_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t q2i__count_response__pack_to_buffer
                     (const Q2i__CountResponse *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__count_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Q2i__CountResponse *
       q2i__count_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Q2i__CountResponse *)
     protobuf_c_message_unpack (&q2i__count_response__descriptor,
                                allocator, len, data);
}
void   q2i__count_response__free_unpacked
                     (Q2i__CountResponse *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__count_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   q2i__span__init
                     (Q2i__Span         *message)
{
  static Q2i__Span init_value = Q2I__SPAN__INIT;
  *message = init_value;
}
size_t q2i__span__get_packed_size
                     (const Q2i__Span *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__span__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t q2i__span__pack
                     (const Q2i__Span *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__span__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t q2i__span__pack_to_buffer
                     (const Q2i__Span *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__span__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Q2i__Span *
       q2i__span__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Q2i__Span *)
     protobuf_c_message_unpack (&q2i__span__descriptor,
                                allocator, len, data);
}
void   q2i__span__free_unpacked
                     (Q2i__Span *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__span__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   q2i__range__init
                     (Q2i__Range         *message)
{
  static Q2i__Range init_value = Q2I__RANGE__INIT;
  *message = init_value;
}
size_t q2i__range__get_packed_size
                     (const Q2i__Range *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__range__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t q2i__range__pack
                     (const Q2i__Range *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__range__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t q2i__range__pack_to_buffer
                     (const Q2i__Range *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__range__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Q2i__Range *
       q2i__range__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Q2i__Range *)
     protobuf_c_message_unpack (&q2i__range__descriptor,
                                allocator, len, data);
}
void   q2i__range__free_unpacked
                     (Q2i__Range *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__range__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   q2i__index_entry__init
                     (Q2i__IndexEntry         *message)
{
  static Q2i__IndexEntry init_value = Q2I__INDEX_ENTRY__INIT;
  *message = init_value;
}
size_t q2i__index_entry__get_packed_size
                     (const Q2i__IndexEntry *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__index_entry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t q2i__index_entry__pack
                     (const Q2i__IndexEntry *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__index_entry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t q2i__index_entry__pack_to_buffer
                     (const Q2i__IndexEntry *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__index_entry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Q2i__IndexEntry *
       q2i__index_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Q2i__IndexEntry *)
     protobuf_c_message_unpack (&q2i__index_entry__descriptor,
                                allocator, len, data);
}
void   q2i__index_entry__free_unpacked
                     (Q2i__IndexEntry *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__index_entry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   q2i__index_statistics__init
                     (Q2i__IndexStatistics         *message)
{
  static Q2i__IndexStatistics init_value = Q2I__INDEX_STATISTICS__INIT;
  *message = init_value;
}
size_t q2i__index_statistics__get_packed_size
                     (const Q2i__IndexStatistics *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__index_statistics__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t q2i__index_statistics__pack
                     (const Q2i__IndexStatistics *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__index_statistics__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t q2i__index_statistics__pack_to_buffer
                     (const Q2i__IndexStatistics *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__index_statistics__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Q2i__IndexStatistics *
       q2i__index_statistics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Q2i__IndexStatistics *)
     protobuf_c_message_unpack (&q2i__index_statistics__descriptor,
                                allocator, len, data);
}
void   q2i__index_statistics__free_unpacked
                     (Q2i__IndexStatistics *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &q2i__index_statistics__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor q2i__error__field_descriptors[1] =
{
  {
    "error",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__Error, error),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned q2i__error__field_indices_by_name[] = {
  0,   /* field[0] = error */
};
static const ProtobufCIntRange q2i__error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor q2i__error__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "q2i.Error",
  "Error",
  "Q2i__Error",
  "q2i",
  sizeof(Q2i__Error),
  1,
  q2i__error__field_descriptors,
  q2i__error__field_indices_by_name,
  1,  q2i__error__number_ranges,
  (ProtobufCMessageInit) q2i__error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor q2i__query_payload__field_descriptors[10] =
{
  {
    "version",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__QueryPayload, version),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "statisticsRequest",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__QueryPayload, statisticsrequest),
    &q2i__statistics_request__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "statistics",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__QueryPayload, statistics),
    &q2i__statistics_response__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scanRequest",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__QueryPayload, scanrequest),
    &q2i__scan_request__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scanAllRequest",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__QueryPayload, scanallrequest),
    &q2i__scan_all_request__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stream",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__QueryPayload, stream),
    &q2i__response_stream__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "countRequest",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__QueryPayload, countrequest),
    &q2i__count_request__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "countResponse",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__QueryPayload, countresponse),
    &q2i__count_response__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "endStream",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__QueryPayload, endstream),
    &q2i__end_stream_request__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "streamEnd",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__QueryPayload, streamend),
    &q2i__stream_end_response__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned q2i__query_payload__field_indices_by_name[] = {
  6,   /* field[6] = countRequest */
  7,   /* field[7] = countResponse */
  8,   /* field[8] = endStream */
  4,   /* field[4] = scanAllRequest */
  3,   /* field[3] = scanRequest */
  2,   /* field[2] = statistics */
  1,   /* field[1] = statisticsRequest */
  5,   /* field[5] = stream */
  9,   /* field[9] = streamEnd */
  0,   /* field[0] = version */
};
static const ProtobufCIntRange q2i__query_payload__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor q2i__query_payload__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "q2i.QueryPayload",
  "QueryPayload",
  "Q2i__QueryPayload",
  "q2i",
  sizeof(Q2i__QueryPayload),
  10,
  q2i__query_payload__field_descriptors,
  q2i__query_payload__field_indices_by_name,
  1,  q2i__query_payload__number_ranges,
  (ProtobufCMessageInit) q2i__query_payload__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor q2i__statistics_request__field_descriptors[3] =
{
  {
    "span",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__StatisticsRequest, span),
    &q2i__span__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indexName",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__StatisticsRequest, indexname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bucket",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__StatisticsRequest, bucket),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned q2i__statistics_request__field_indices_by_name[] = {
  2,   /* field[2] = bucket */
  1,   /* field[1] = indexName */
  0,   /* field[0] = span */
};
static const ProtobufCIntRange q2i__statistics_request__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 3, 1 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor q2i__statistics_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "q2i.StatisticsRequest",
  "StatisticsRequest",
  "Q2i__StatisticsRequest",
  "q2i",
  sizeof(Q2i__StatisticsRequest),
  3,
  q2i__statistics_request__field_descriptors,
  q2i__statistics_request__field_indices_by_name,
  2,  q2i__statistics_request__number_ranges,
  (ProtobufCMessageInit) q2i__statistics_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor q2i__statistics_response__field_descriptors[2] =
{
  {
    "stats",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__StatisticsResponse, stats),
    &q2i__index_statistics__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "err",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__StatisticsResponse, err),
    &q2i__error__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned q2i__statistics_response__field_indices_by_name[] = {
  1,   /* field[1] = err */
  0,   /* field[0] = stats */
};
static const ProtobufCIntRange q2i__statistics_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor q2i__statistics_response__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "q2i.StatisticsResponse",
  "StatisticsResponse",
  "Q2i__StatisticsResponse",
  "q2i",
  sizeof(Q2i__StatisticsResponse),
  2,
  q2i__statistics_response__field_descriptors,
  q2i__statistics_response__field_indices_by_name,
  1,  q2i__statistics_response__number_ranges,
  (ProtobufCMessageInit) q2i__statistics_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor q2i__scan_request__field_descriptors[6] =
{
  {
    "span",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__ScanRequest, span),
    &q2i__span__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "distinct",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__ScanRequest, distinct),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "limit",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__ScanRequest, limit),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pageSize",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__ScanRequest, pagesize),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indexName",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__ScanRequest, indexname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bucket",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__ScanRequest, bucket),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned q2i__scan_request__field_indices_by_name[] = {
  5,   /* field[5] = bucket */
  1,   /* field[1] = distinct */
  4,   /* field[4] = indexName */
  2,   /* field[2] = limit */
  3,   /* field[3] = pageSize */
  0,   /* field[0] = span */
};
static const ProtobufCIntRange q2i__scan_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor q2i__scan_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "q2i.ScanRequest",
  "ScanRequest",
  "Q2i__ScanRequest",
  "q2i",
  sizeof(Q2i__ScanRequest),
  6,
  q2i__scan_request__field_descriptors,
  q2i__scan_request__field_indices_by_name,
  1,  q2i__scan_request__number_ranges,
  (ProtobufCMessageInit) q2i__scan_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor q2i__scan_all_request__field_descriptors[4] =
{
  {
    "pageSize",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__ScanAllRequest, pagesize),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "limit",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__ScanAllRequest, limit),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indexName",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__ScanAllRequest, indexname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bucket",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__ScanAllRequest, bucket),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned q2i__scan_all_request__field_indices_by_name[] = {
  3,   /* field[3] = bucket */
  2,   /* field[2] = indexName */
  1,   /* field[1] = limit */
  0,   /* field[0] = pageSize */
};
static const ProtobufCIntRange q2i__scan_all_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor q2i__scan_all_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "q2i.ScanAllRequest",
  "ScanAllRequest",
  "Q2i__ScanAllRequest",
  "q2i",
  sizeof(Q2i__ScanAllRequest),
  4,
  q2i__scan_all_request__field_descriptors,
  q2i__scan_all_request__field_indices_by_name,
  1,  q2i__scan_all_request__number_ranges,
  (ProtobufCMessageInit) q2i__scan_all_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define q2i__end_stream_request__field_descriptors NULL
#define q2i__end_stream_request__field_indices_by_name NULL
#define q2i__end_stream_request__number_ranges NULL
const ProtobufCMessageDescriptor q2i__end_stream_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "q2i.EndStreamRequest",
  "EndStreamRequest",
  "Q2i__EndStreamRequest",
  "q2i",
  sizeof(Q2i__EndStreamRequest),
  0,
  q2i__end_stream_request__field_descriptors,
  q2i__end_stream_request__field_indices_by_name,
  0,  q2i__end_stream_request__number_ranges,
  (ProtobufCMessageInit) q2i__end_stream_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor q2i__response_stream__field_descriptors[2] =
{
  {
    "indexEntries",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Q2i__ResponseStream, n_indexentries),
    PROTOBUF_C_OFFSETOF(Q2i__ResponseStream, indexentries),
    &q2i__index_entry__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "err",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__ResponseStream, err),
    &q2i__error__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned q2i__response_stream__field_indices_by_name[] = {
  1,   /* field[1] = err */
  0,   /* field[0] = indexEntries */
};
static const ProtobufCIntRange q2i__response_stream__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor q2i__response_stream__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "q2i.ResponseStream",
  "ResponseStream",
  "Q2i__ResponseStream",
  "q2i",
  sizeof(Q2i__ResponseStream),
  2,
  q2i__response_stream__field_descriptors,
  q2i__response_stream__field_indices_by_name,
  1,  q2i__response_stream__number_ranges,
  (ProtobufCMessageInit) q2i__response_stream__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor q2i__stream_end_response__field_descriptors[1] =
{
  {
    "err",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__StreamEndResponse, err),
    &q2i__error__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned q2i__stream_end_response__field_indices_by_name[] = {
  0,   /* field[0] = err */
};
static const ProtobufCIntRange q2i__stream_end_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor q2i__stream_end_response__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "q2i.StreamEndResponse",
  "StreamEndResponse",
  "Q2i__StreamEndResponse",
  "q2i",
  sizeof(Q2i__StreamEndResponse),
  1,
  q2i__stream_end_response__field_descriptors,
  q2i__stream_end_response__field_indices_by_name,
  1,  q2i__stream_end_response__number_ranges,
  (ProtobufCMessageInit) q2i__stream_end_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor q2i__count_request__field_descriptors[2] =
{
  {
    "indexName",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__CountRequest, indexname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bucket",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__CountRequest, bucket),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned q2i__count_request__field_indices_by_name[] = {
  1,   /* field[1] = bucket */
  0,   /* field[0] = indexName */
};
static const ProtobufCIntRange q2i__count_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor q2i__count_request__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "q2i.CountRequest",
  "CountRequest",
  "Q2i__CountRequest",
  "q2i",
  sizeof(Q2i__CountRequest),
  2,
  q2i__count_request__field_descriptors,
  q2i__count_request__field_indices_by_name,
  1,  q2i__count_request__number_ranges,
  (ProtobufCMessageInit) q2i__count_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor q2i__count_response__field_descriptors[2] =
{
  {
    "count",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__CountResponse, count),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "err",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__CountResponse, err),
    &q2i__error__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned q2i__count_response__field_indices_by_name[] = {
  0,   /* field[0] = count */
  1,   /* field[1] = err */
};
static const ProtobufCIntRange q2i__count_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor q2i__count_response__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "q2i.CountResponse",
  "CountResponse",
  "Q2i__CountResponse",
  "q2i",
  sizeof(Q2i__CountResponse),
  2,
  q2i__count_response__field_descriptors,
  q2i__count_response__field_indices_by_name,
  1,  q2i__count_response__number_ranges,
  (ProtobufCMessageInit) q2i__count_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor q2i__span__field_descriptors[2] =
{
  {
    "range",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__Span, range),
    &q2i__range__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "equal",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    PROTOBUF_C_OFFSETOF(Q2i__Span, n_equal),
    PROTOBUF_C_OFFSETOF(Q2i__Span, equal),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned q2i__span__field_indices_by_name[] = {
  1,   /* field[1] = equal */
  0,   /* field[0] = range */
};
static const ProtobufCIntRange q2i__span__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor q2i__span__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "q2i.Span",
  "Span",
  "Q2i__Span",
  "q2i",
  sizeof(Q2i__Span),
  2,
  q2i__span__field_descriptors,
  q2i__span__field_indices_by_name,
  1,  q2i__span__number_ranges,
  (ProtobufCMessageInit) q2i__span__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor q2i__range__field_descriptors[3] =
{
  {
    "low",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__Range, low),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "high",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__Range, high),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inclusion",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__Range, inclusion),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned q2i__range__field_indices_by_name[] = {
  1,   /* field[1] = high */
  2,   /* field[2] = inclusion */
  0,   /* field[0] = low */
};
static const ProtobufCIntRange q2i__range__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor q2i__range__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "q2i.Range",
  "Range",
  "Q2i__Range",
  "q2i",
  sizeof(Q2i__Range),
  3,
  q2i__range__field_descriptors,
  q2i__range__field_indices_by_name,
  1,  q2i__range__number_ranges,
  (ProtobufCMessageInit) q2i__range__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor q2i__index_entry__field_descriptors[2] =
{
  {
    "entryKey",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__IndexEntry, entrykey),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "primaryKey",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__IndexEntry, primarykey),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned q2i__index_entry__field_indices_by_name[] = {
  0,   /* field[0] = entryKey */
  1,   /* field[1] = primaryKey */
};
static const ProtobufCIntRange q2i__index_entry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor q2i__index_entry__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "q2i.IndexEntry",
  "IndexEntry",
  "Q2i__IndexEntry",
  "q2i",
  sizeof(Q2i__IndexEntry),
  2,
  q2i__index_entry__field_descriptors,
  q2i__index_entry__field_indices_by_name,
  1,  q2i__index_entry__number_ranges,
  (ProtobufCMessageInit) q2i__index_entry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor q2i__index_statistics__field_descriptors[4] =
{
  {
    "keysCount",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__IndexStatistics, keyscount),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uniqueKeysCount",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__IndexStatistics, uniquekeyscount),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keyMin",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__IndexStatistics, keymin),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keyMax",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Q2i__IndexStatistics, keymax),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned q2i__index_statistics__field_indices_by_name[] = {
  3,   /* field[3] = keyMax */
  2,   /* field[2] = keyMin */
  0,   /* field[0] = keysCount */
  1,   /* field[1] = uniqueKeysCount */
};
static const ProtobufCIntRange q2i__index_statistics__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor q2i__index_statistics__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "q2i.IndexStatistics",
  "IndexStatistics",
  "Q2i__IndexStatistics",
  "q2i",
  sizeof(Q2i__IndexStatistics),
  4,
  q2i__index_statistics__field_descriptors,
  q2i__index_statistics__field_indices_by_name,
  1,  q2i__index_statistics__number_ranges,
  (ProtobufCMessageInit) q2i__index_statistics__init,
  NULL,NULL,NULL    /* reserved[123] */
};
